// Generated by Unloop
// Office Climate Control

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_schedule_clicked(|| {
        println!("schedule clicked");
    });
    
    app.on_away_clicked(|| {
        println!("away clicked");
    });
    

    
    app.run()
}
